routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['web']], function(){
    Route::get('/all-booking', 'App\Http\Controllers\BookingController@index')->name('all-booking');
    Route::get('/users-booking', 'App\Http\Controllers\BookingController@usersBookingInfo')->name('users-booking');
    //Bookings
    Route::resource('bookings', \App\Http\Controllers\BookingController::class);
    //Hotels
    Route::resource('hotels', \App\Http\Controllers\HotelController::class);
});

app/Models/Booking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\User;

class Booking extends Model
{
    use HasFactory;

    protected $table = 'bookings';

    public function users()
    {
        return $this->belongsTo('App\Models\User');
    }

}

app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreBookingRequest;
use App\Http\Requests\UpdateBookingRequest;
use App\Models\Booking;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use function response;
use Exception;
use App\Services\BookingService;
use Carbon\Carbon;
use App\Models\Hotel;

class BookingController extends Controller
{
    protected $bookingService;

    /**
     * BookingController Constructor
     *
     * @param BookingService $bookingService
     *
     */
    public function __construct(BookingService $bookingService)
    {
        $this->bookingService = $bookingService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $result = ['status' => 200];

        try {
            $result['data'] = $this->bookingService->getAll();
        } catch (Exception $e) {
            $result = [
                'status' => 500,
                'error' => $e->getMessage()
            ];
        }

        return view('bookings.all-bookings')->withBookings($result['data']);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $hotels = Hotel::all();

        return view('bookings.create-booking')->withHotels($hotels);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreBookingRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->only([
            'room_name',
            'title',
            'hotel_id',
            'start_date',
            'end_date',
        ]);

        $data['user_id'] = Auth::user()->id;
        $result = ['status' => 200];

        try {
            $result['data'] = $this->bookingService->saveBookingData($data);
            $result['view'] = 'bookings.show-bookings';
            $result['success'] = 'New booking successfully saved';

        } catch (Exception $e) {
            $result = [
                'status' => 500,
                'error' => $e->getMessage(),
                'view' => 'bookings.create-booking'
            ];
        }

        return view($result['view'],[
            'booking' => (!empty($result['data'])) ? $result['data'] : '',
            'status' => $result['status'],
            'message' => (!empty($result['success'])) ? $result['success'] : $result['error'],
            'hotels' => $hotels = Hotel::all()
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $booking = $this->bookingService->getBookingById($id);

        return view('bookings.show-bookings')->withBooking($booking);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $hotels = Hotel::all();

        $result = ['status' => 200];

        try {
            $result['data'] = $this->bookingService->getBookingById($id);
        } catch (Exception $e) {
            $result = [
                'status' => 500,
                'error' => $e->getMessage()
            ];
        }

        $result['data']->start_date = Carbon::parse($result['data']->start_date)->format('Y-m-d');
        $result['data']->end_date = Carbon::parse($result['data']->end_date)->format('Y-m-d');

        return view('bookings.edit-booking')->withBooking($result['data'])->withHotels($hotels);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateBookingRequest  $request
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $data = $request->only([
            'room_name',
            'title',
            'hotel_id',
            'start_date',
            'end_date',
        ]);

        $result = ['status' => 200];

        try {
            $this->bookingService->updateBooking($data, $id);
            $result['view'] = 'bookings.show-bookings';
            $result['success'] = 'Booking was updated successfully';
        } catch (Exception $e) {
            $result = [
                'status' => 500,
                'error' => $e->getMessage(),
                'view' => 'bookings.edit-booking'
            ];
        }
        $result['booking'] = $this->bookingService->getBookingById($id);

        return view($result['view'],[
            'booking' => $result['booking'],
            'status' => $result['status'],
            'message' => (!empty($result['success'])) ? $result['success'] : $result['error'],
            'hotels' => $hotels = Hotel::all()
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = ['status' => 200];

        try {
            $result['data'] = $this->bookingService->deleteById($id);
            $result['success'] = 'Booking was deleted successfully';
        } catch (Exception $e) {
            $result = [
              'status' => 500,
              'error' => $e->getMessage()
            ];
        }

        return redirect()->route('bookings.index')->with('status', $result['success']);

    }

    public function showBookingByUser(Request $request)
    {
        $login = $request->validate([
            'email'    => 'required|string',
            'password' => 'required|string',
        ]);

        if (!Auth::attempt($login)) {
            return response(['message' => 'Invalid login credentials!']);
        }

        $user = Auth::user();
        $bookingByUser = $user->bookings;

        return response(['user' => Auth::user(), 'bookings' => $bookingByUser]);

    }

    public function showBookingInfoByUser(Request $request)
    {
        $result = Auth::guard('api')->user()->id;
        $results = Booking::select('id', 'user_id', 'room_name')->where('user_id', '=', $result)->get();

        return response(['user' => $results]);
    }

    public function usersBookingInfo()
    {
        $userId = Auth::user()->id;

        $result = ['status' => 200];

        try {
            $result['data'] = $this->bookingService->getByUserId($userId);
        } catch (Exception $e) {
            $result = [
                'status' => 500,
                'error' => $e->getMessage()
            ];
        }

        return view('bookings.user-booking')->withBookings($result['data']);;
    }

    public function destroyBooking(Request $request)
    {
        $bookingId = $request->input('id');
        $result = ['status' => 200];

        try {
            $result['data'] = $this->bookingService->deleteById($bookingId);
        } catch (Exception $e) {
            $result = [
                'status' => 500,
                'error' => $e->getMessage()
            ];
        }
        return response()->json($result, $result['status']);

    }
}

resources/views/bookings/all-bookings.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="col-md-4">
                    <a href="{{ route('bookings.create') }}" class="btn btn-sm btn-primary mb-4 mt-1" role="button">New Booking</a>
                </div>
                <div class="card">
                    @if (isset($message))
                        <div class="col-md-12 alert-success">
                            {{ $message }}
                        </div>
                    @endif
                    <div class="card-header">{{ __('All Bookings') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if ($bookings->count() > 0)
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Room Name</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Start Date</th>
                                    <th scope="col">End Date</th>
                                    <th scope="col"></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($bookings as $booking)
                                    <tr>
                                        <td>{{ $booking->id }}</td>
                                        <td>{{ $booking->room_name }}</td>
                                        <td>{{ $booking->title }}</td>
                                        <td>{{ $booking->start_date }}</td>
                                        <td>{{ $booking->end_date }}</td>
                                        <td> <div class="col-md-3 custom">
                                                <form action="{{ route('bookings.destroy', ['booking' => $booking->id]) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                                </form>
                                            </div></td>
                                        <td><a href="{{ route('bookings.edit', $booking->id) }}" class="btn btn-info">Edit</a></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bookings/create-booking.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (isset($message))
            <div class="col-md-12 alert-danger">
                {{ $message }}
            </div>
        @endif
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                <h2 class="bg-dark text-white-50 p-3">New Booking</h2>

                {!! Form::open(['route' => ['bookings.store']]) !!}

                {{ Form::label('room_name', 'Room Name:') }}
                {{ Form::text('room_name', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '15')) }}

                {{ Form::label('title', 'Title:', array('class' => 'mt-3')) }}
                {{ Form::text('title', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255')) }}

                {{ Form::label('hotel_id', 'Hotel:', array('class' => 'mt-3')) }}
                <select class="form-control" id="hotel" name="hotel_id">
                    <option value="">Select Hotel</option>
                    @foreach($hotels as $hotel)
                        <option value="{{$hotel->id}}">{{$hotel->hotel_name}}</option>
                    @endforeach
                </select>

                {{ Form::label('start_date', 'Start Date:', array('class' => 'mt-3')) }}
                {{ Form::input('date', 'start_date', null, array('class' => 'form-control', 'min' => '2010-01-01', 'max' => '2025-12-31')) }}

                {{ Form::label('end_date', 'End Date:', array('class' => 'mt-3')) }}
                {{ Form::input('date', 'end_date', null, array('class' => 'form-control', 'min' => '2010-01-01', 'max' => '2025-12-31')) }}

                <div class="row mt-3">
                    <div class="col-sm-3">
                        {{ Form::submit('Save Changes', ['class' => 'btn btn-success btn-block']) }}
                    </div>
                </div>
                {{ Form::close() }}
            </div>
        </div>

@endsection

resources/views/bookings/edit-booking.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

<div class="row">
    <div class="col-md-8 col-md-offset-2">

        <h2 class="bg-dark text-white-50 p-3">Edit Booking</h2>
        @if (isset($message))
            <div class="col-md-12 alert-danger">
                {{ $message }}
            </div>
        @endif
        {!! Form::model($booking, ['route' => ['bookings.update', $booking->id], 'method' => 'PUT']) !!}

        {{ Form::label('room_name', 'Room Name:') }}
        {!! Form::text('room_name', null, ['class' => 'form-control input-lg']) !!}

        {{ Form::label('title', 'Title:', array('class' => 'mt-3')) }}
        {{ Form::text('title', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255')) }}

        {{ Form::label('hotel_id', 'Hotel:', array('class' => 'mt-2')) }}
        <select class="form-control" name="hotel_id">
            <option value="">Select Hotel</option>
            @foreach($hotels as $hotel)
                <option value="{{($hotel->id === $booking->hotel_id) ? $booking->hotel_id : $hotel->id}}" {{ ($hotel->id === $booking->hotel_id) ? 'selected' : ''}}>{{$hotel->hotel_name}}</option>
            @endforeach
        </select>

        {{ Form::label('start_date', 'Start Date:', array('class' => 'mt-3')) }}
        {{ Form::input('date', 'start_date', null, array('class' => 'form-control', 'min' => '2010-01-01', 'max' => '2025-12-31')) }}

        {{ Form::label('end_date', 'End Date:', array('class' => 'mt-3')) }}
        {{ Form::input('date', 'end_date', null, array('class' => 'form-control', 'min' => '2010-01-01', 'max' => '2025-12-31')) }}

        <div class="row mt-3">
            <div class="col-sm-3">
                {!! Html::linkRoute('bookings.show', 'Cancel', array($booking->id), array('class'=> 'btn btn-danger btn-block')) !!}
            </div>
            <div class="col-sm-3">
                {{ Form::submit('Save Changes', ['class' => 'btn btn-success btn-block']) }}
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/bookings/show-bookings.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @if (isset($message))
                <div class="col-md-12 alert-info">
                    {{ $message }}
                </div>
            @endif
        <div class="col-md-12 ">

            <h2>{{ $booking['room_name'] }}</h2>

            <hr/>
        </div>
        <div class="col-md-4 border bg-dark text-white-50">
            <div class="well mt-3">

                <dl class="dl-horizontal">
                    <label>Title:</label>
                    <p class="text-white">{{ $booking->title }}</p>
                </dl>

                <dl class="dl-horizontal">
                    <label>Start Date:</label>
                    <p class="text-white">{{ date('M j, Y h:ia', strtotime($booking->start_date)) }}</p>
                </dl>

                <dl class="dl-horizontal">
                    <label>End Date:</label>
                    <p class="text-white">{{ date('M j, Y h:ia', strtotime($booking->end_date)) }}</p>
                </dl>
                <hr>

                <div class="row mb-3">
                    <div class="col-sm-8">
                        {!! Html::linkRoute('bookings.edit', 'Edit', array($booking->id), array('class'=> 'btn btn-primary btn-block')) !!}
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
@endsection

resources/views/bookings/user-booking.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('All Bookings') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if ($bookings->count() > 0)
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">User Id</th>
                                    <th scope="col">Booking Id</th>
                                    <th scope="col">User Name</th>
                                    <th scope="col">Room Name</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Start Date</th>
                                    <th scope="col">End Date</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @foreach($bookings as $booking)
                                    <tr>
                                        <td>{{ $booking->id }}</td>
                                        <td>{{ $booking->booking_id }}</td>
                                        <td>{{ $booking->name }}</td>
                                        <td>{{ $booking->room_name }}</td>
                                        <td>{{ $booking->title }}</td>
                                        <td>{{ $booking->start_date }}</td>
                                        <td>{{ $booking->end_date }}</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection