routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['web']], function(){
    Route::get('/all-booking', 'App\Http\Controllers\BookingController@index')->name('all-booking');
    Route::get('/users-booking', 'App\Http\Controllers\BookingController@usersBookingInfo')->name('users-booking');
    //Bookings
    Route::resource('bookings', \App\Http\Controllers\BookingController::class);
    //Hotels
    Route::resource('hotels', \App\Http\Controllers\HotelController::class);
});

app/Models/Hotel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Hotel extends Model
{
    use HasFactory;
}

app/Http/Controllers/HotelController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreHotelRequest;
use App\Http\Requests\UpdateHotelRequest;
use App\Models\Hotel;
use App\Services\HotelService;
use Illuminate\Http\Request;
use Exception;

class HotelController extends Controller
{
    protected $hotelService;

    /**
     * HotelController Constructor
     *
     * @param HotelService $hotelService
     *
     */
    public function __construct(HotelService $hotelService)
    {
        $this->hotelService = $hotelService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $result = ['status' => 200];

        try {
            $result['data'] = $this->hotelService->getAll();
        } catch (Exception $e) {
            $result = [
                'status' => 500,
                'error' => $e->getMessage()
            ];
        }

        return view('hotels.all-hotels')->withHotels($result['data']);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('hotels.create-hotel');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreHotelRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->only([
            'hotel_name',
            'floor',
            'rooms_number',
        ]);


        $result = ['status' => 200];

        try {
            $result['data'] = $this->hotelService->saveHotelData($data);
            $result['view'] = 'hotels.show-hotels';
            $result['success'] = 'New hotel successfully saved';

        } catch (Exception $e) {
            $result = [
                'status' => 500,
                'error' => $e->getMessage(),
                'view' => 'hotels.create-hotel'
            ];
        }

        return view($result['view'],[
            'hotel' => (!empty($result['data'])) ? $result['data'] : '',
            'status' => $result['status'],
            'message' => (!empty($result['success'])) ? $result['success'] : $result['error'],
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Hotel  $hotel
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $hotel = $this->hotelService->getHotelById($id);

        return view('hotels.show-hotels')->withHotel($hotel);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Hotel  $hotel
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $result = ['status' => 200];

        try {
            $result['data'] = $this->hotelService->getHotelById($id);
        } catch (Exception $e) {
            $result = [
                'status' => 500,
                'error' => $e->getMessage()
            ];
        }

        return view('hotels.edit-hotel')->withHotel($result['data']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateHotelRequest  $request
     * @param  \App\Models\Hotel  $hotel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->only([
            'hotel_name',
            'floor',
            'rooms_number',
        ]);

        $result = ['status' => 200];

        try {
            $result['data'] = $this->hotelService->updateHotel($data, $id);
            $result['view'] = 'hotels.show-hotels';
            $result['success'] = 'Hotel was updated successfully';
        } catch (Exception $e) {
            $result = [
                'status' => 500,
                'error' => $e->getMessage(),
                'view' => 'hotels.edit-hotel'
            ];
        }

        $result['hotel'] = $this->hotelService->getHotelById($id);

        return view($result['view'],[
            'hotel' => $result['hotel'],
            'status' => $result['status'],
            'message' => (!empty($result['success'])) ? $result['success'] : $result['error'],
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Hotel  $hotel
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = ['status' => 200];

        try {
            $this->hotelService->deleteById($id);
            $result['success'] = 'Hotel was deleted successfully';
        } catch (Exception $e) {
            $result = [
                'status' => 500,
                'error' => $e->getMessage()
            ];
        }

        return redirect()->route('hotels.index')->with('status', $result['success']);

    }
}

resources/views/hotels/all-hotels.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="col-md-4">
                    <a href="{{ route('hotels.create') }}" class="btn btn-sm btn-primary mb-4 mt-1" role="button">New Hotel</a>
                </div>
                <div class="card">
                    @if (isset($message))
                        <div class="col-md-12 alert-success">
                            {{ $message }}
                        </div>
                    @endif
                    <div class="card-header">{{ __('All Hotels') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if ($hotels->count() > 0)
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Hotel Name</th>
                                    <th scope="col">Floor</th>
                                    <th scope="col">Rooms Number</th>
                                    <th scope="col"></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($hotels as $hotel)
                                    <tr>
                                        <td>{{ $hotel->id }}</td>
                                        <td>{{ $hotel->hotel_name }}</td>
                                        <td>{{ $hotel->floor }}</td>
                                        <td>{{ $hotel->rooms_number }}</td>
                                        <td> <div class="col-md-3 custom">
                                                <form action="{{ route('hotels.destroy', ['hotel' => $hotel->id]) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                                </form>
                                            </div></td>
                                        <td><a href="{{ route('hotels.edit', $hotel->id) }}" class="btn btn-info">Edit</a></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/hotels/create-hotel.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (isset($message))
            <div class="col-md-12 alert-danger">
                {{ $message }}
            </div>
        @endif
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                <h2 class="bg-dark text-white-50 p-3">New Hotel</h2>

                {!! Form::open(['route' => ['hotels.store']]) !!}

                {{ Form::label('hotel_name', 'Hotel Name:') }}
                {{ Form::text('hotel_name', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '15')) }}

                {{ Form::label('floor', 'Floor:', array('class' => 'mt-3')) }}
                {{ Form::text('floor', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255')) }}

                {{ Form::label('rooms_number', 'Rooms number:', array('class' => 'mt-3')) }}
                {{ Form::input('rooms_number', 'rooms_number', null, array('class' => 'form-control')) }}

                <div class="row mt-3">
                    <div class="col-sm-3">
                        {{ Form::submit('Save Changes', ['class' => 'btn btn-success btn-block']) }}
                    </div>
                </div>
                {{ Form::close() }}
            </div>
        </div>

@endsection

resources/views/hotels/edit-hotel.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                <h2 class="bg-dark text-white-50 p-3">Edit Hotel</h2>
                @if (isset($message))
                    <div class="col-md-12 alert-danger">
                        {{ $message }}
                    </div>
                @endif
                {!! Form::model($hotel, ['route' => ['hotels.update', $hotel->id], 'method' => 'PUT']) !!}

                {{ Form::label('hotel_name', 'Hotel Name:') }}
                {{ Form::text('hotel_name', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '15')) }}

                {{ Form::label('floor', 'Floor:', array('class' => 'mt-3')) }}
                {{ Form::text('floor', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255')) }}

                {{ Form::label('rooms_number', 'Rooms number:', array('class' => 'mt-3')) }}
                {{ Form::input('rooms_number', 'rooms_number', null, array('class' => 'form-control')) }}

                <div class="row mt-3">
                    <div class="col-sm-3">
                        {!! Html::linkRoute('hotels.show', 'Cancel', array($hotel->id), array('class'=> 'btn btn-danger btn-block')) !!}
                    </div>
                    <div class="col-sm-3">
                        {{ Form::submit('Save Changes', ['class' => 'btn btn-success btn-block']) }}
                    </div>
                </div>
            </div>
        </div>

@endsection

resources/views/hotels/show-hotels.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @if (isset($message))
                <div class="col-md-12 alert-info">
                    {{ $message }}
                </div>
            @endif
            <div class="col-md-12 ">

                <h2>{{ $hotel['hotel_name'] }}</h2>

                <hr/>
            </div>
            <div class="col-md-4 border bg-dark text-white-50">
                <div class="well mt-3">

                    <dl class="dl-horizontal">
                        <label>Title:</label>
                        <p class="text-white">{{ $hotel->floor }}</p>
                    </dl>

                    <dl class="dl-horizontal">
                        <label>Title:</label>
                        <p class="text-white">{{ $hotel->floor }}</p>
                    </dl>

                    <div class="row mb-3">
                        <div class="col-sm-8">
                            {!! Html::linkRoute('hotels.edit', 'Edit', array($hotel->id), array('class'=> 'btn btn-primary btn-block')) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection